// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXtqFpjC5Oh0DzLmVGzIkeM2-vswKCRE',
    appId: '1:36559275739:web:f74655a8a3d5b56355aefe',
    messagingSenderId: '36559275739',
    projectId: 'expenseincomeapp',
    authDomain: 'expenseincomeapp.firebaseapp.com',
    storageBucket: 'expenseincomeapp.appspot.com',
    measurementId: 'G-9EX76G32J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCko9FLffuraGso7KT3Tko3Acv64cycnWo',
    appId: '1:36559275739:android:cba930c4575e5e1055aefe',
    messagingSenderId: '36559275739',
    projectId: 'expenseincomeapp',
    storageBucket: 'expenseincomeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYEcd5PeU7Mx09TJQzfd0f6QqTLnj_t8',
    appId: '1:36559275739:ios:3c210e9963ae182555aefe',
    messagingSenderId: '36559275739',
    projectId: 'expenseincomeapp',
    storageBucket: 'expenseincomeapp.appspot.com',
    iosClientId: '36559275739-3p6ff8c4nqnosrvuntg5nid917nrr2p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXYEcd5PeU7Mx09TJQzfd0f6QqTLnj_t8',
    appId: '1:36559275739:ios:3c210e9963ae182555aefe',
    messagingSenderId: '36559275739',
    projectId: 'expenseincomeapp',
    storageBucket: 'expenseincomeapp.appspot.com',
    iosClientId: '36559275739-3p6ff8c4nqnosrvuntg5nid917nrr2p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
