// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVfQogMHdZEGkwXJ32yf3x-fEsg7Ss394',
    appId: '1:330272412409:android:51c7e1729b554947c8c828',
    messagingSenderId: '330272412409',
    projectId: 'cunehat',
    storageBucket: 'cunehat.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsFyYhBtlHITcQD23lktK0Ek9z-4KqJ4',
    appId: '1:330272412409:web:33d9228153207401c8c828',
    messagingSenderId: '330272412409',
    projectId: 'cunehat',
    authDomain: 'cunehat.firebaseapp.com',
    storageBucket: 'cunehat.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9OshKvHoAHmK65xYW-YZEgNVSwQwANM',
    appId: '1:330272412409:ios:e8c5edfa227731b6c8c828',
    messagingSenderId: '330272412409',
    projectId: 'cunehat',
    storageBucket: 'cunehat.firebasestorage.app',
    androidClientId: '330272412409-2mhij3mh9p12rmtdujbpjg6vuilfl59r.apps.googleusercontent.com',
    iosClientId: '330272412409-n0ktel712qp3019r36vl6h67vfrnghn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cunehat',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9OshKvHoAHmK65xYW-YZEgNVSwQwANM',
    appId: '1:330272412409:ios:e8c5edfa227731b6c8c828',
    messagingSenderId: '330272412409',
    projectId: 'cunehat',
    storageBucket: 'cunehat.firebasestorage.app',
    androidClientId: '330272412409-2mhij3mh9p12rmtdujbpjg6vuilfl59r.apps.googleusercontent.com',
    iosClientId: '330272412409-n0ktel712qp3019r36vl6h67vfrnghn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cunehat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcsFyYhBtlHITcQD23lktK0Ek9z-4KqJ4',
    appId: '1:330272412409:web:3296b5d0e01d4715c8c828',
    messagingSenderId: '330272412409',
    projectId: 'cunehat',
    authDomain: 'cunehat.firebaseapp.com',
    storageBucket: 'cunehat.firebasestorage.app',
  );

}